GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.%' IDENTIFIED BY '19710819' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON app_front_office.* TO 'front_office'@'192.168.%' IDENTIFIED BY 'Qwerty' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON app_zm.* TO 'zm_user1'@'192.168.%' IDENTIFIED BY 'zm2015' WITH GRANT OPTION;
